---
- name: DESLIGAR AGORA - Somente PCs Windows (ignorar Windows Server)
  hosts: 
    - todos
  gather_facts: yes

  tasks:
    - name: Desligar apenas Windows Workstation
      win_shell: shutdown /s /f /t 0
      when:
        - (ansible_facts.os_product_type | default('')) == "workstation"

    - name: Ignorar Windows Server
      debug:
        msg: "IGNORADO: {{ inventory_hostname }} é Windows Server (não será desligado)."
      when:
        - (ansible_facts.os_product_type | default('')) != "workstation"
