---
- name: DESLIGAR AGORA - Somente PCs Windows (ignorar Windows Server)
  hosts: inacom-dafsg-19
  gather_facts: yes
  ignore_unreachable: yes

  tasks:

    - name: Desligar apenas Windows Workstation (Windows 7/8/10/11)
      win_shell: shutdown /s /f /t 0
      when:
        - ansible_facts.os_family == "Windows"
        - "'Server' not in ansible_facts.os_name"

    - name: Ignorar Windows Server
      debug:
        msg: "IGNORADO: {{ inventory_hostname }} é Windows Server (não será desligado)."
      when:
        - ansible_facts.os_family == "Windows"
        - "'Server' in ansible_facts.os_name"
